# $OpenBSD$
COMMENT =	simple file watcher utility for OpenBSD
DISTNAME =	fwa-0.1
CATEGORIES =	sysutils

HOMEPAGE =	http://github.com/peterhajdu/fwa

MAINTAINER =	Peter Hajdu <peter.ferenc.hajdu@gmail.com>

# BSD
PERMIT_PACKAGE_CDROM =	Yes

WANTLIB += c

GH_ACCOUNT =		peterhajdu
GH_PROJECT =		fwa
GH_COMMIT =		822a7bbcab0ad52b09f38fa9838e160481391ef9

MAKE_FILE =	Makefile
FAKE_FLAGS =	DESTDIR=""

TEST_TARGET =	test

.include <bsd.port.mk>
