COMMENT =	simple file watcher utility for OpenBSD
DISTNAME =	fwa-0.2
CATEGORIES =	sysutils

MAINTAINER =	Peter Hajdu <peter@hajdu.im>

# BSD
PERMIT_PACKAGE =	Yes

WANTLIB += c

GH_ACCOUNT =		peterhajdu
GH_PROJECT =		fwa
GH_TAGNAME =		0.2

FAKE_FLAGS =	DESTDIR=""

.include <bsd.port.mk>
